#!/bin/bash
TAG_APP="1.0.0"
NAME_APP="server_signal_call"

printUsage() {
	echo " start: launch the program"
	echo " build: launch the program with build"
	echo " remove: remove docker container"
	echo " stop: kill the program"
	echo " restart: kill the program first, then launch again the program"
	echo " status: show the program is running or stopped"
}

build_image() {
	docker build . -t $NAME_APP:$TAG_APP
}

startApp() {
    docker rm $NAME_APP
    docker run --name $NAME_APP -p 8080:8080 -p 8081:8081 -d $NAME_APP:$TAG_APP
	echo "Start app $NAME_APP" 
}

stopApp() {
	echo "Stoping app $NAME_APP" 
	docker stop $NAME_APP
}

case "$1" in
	build)
		build_image
		;;
	push)
		push_image
		;;
	pull)
		pull_image
		;;
	start)
		startApp
		;;
	stop)
		stopApp
		;;
	status)
		docker ps -a | grep $NAME_APP
		;;
	restart)
		;;
	remove)
		removeService
		;;
	*)
		printUsage
		echo
		exit 1
esac
