#!/bin/bash
TAG_APP="1.0.0"
NAME_APP="server_signal_call"

printUsage() {
	echo "Usage: ./runservice start|stop|restart|status|build|remove|help"
	echo
	echo " The first option is service action:"
	echo " - start: launch the program"
	echo " - build: launch the program with build"
	echo " - remove: remove docker container"
	echo " - stop: kill the program"
	echo " - restart: kill the program first, then launch again the program"
	echo " - status: show the program is running or stopped"
	echo " - help: print this guide"
	echo
}

build_image() {
	docker build . -t $NAME_APP:$TAG_APP
}

launchService() {
	echo "Starting service $NAME_APP......" 
    docker rm $NAME_APP
    docker run --name $NAME_APP -p 800:8080 -p 801:8081 -d $NAME_APP:$TAG_APP
	echo "Done start service $NAME_APP"
}

case "$1" in
	login)
		docker login harbor.infra.zalo.services
		;;
	build)
		build_image
		;;
	push)
		push_image
		;;
	pull)
		pull_image
		;;
	up)
		# checkPylint
		launchService
		;;
	daemon)
		launchServiceDeamon
		checkLaunchService
		;;
	start)
		launchService
		;;
	stop)
		stopService
		;;
	status)
		docker ps -a | grep "ailab/$APP_NAME:" | grep --color=always $APP_NAME
		;;
	lint)
		checkPylint
		;;
	restart)
		$ENTRY_PATH stop $APP_PROF
		$ENTRY_PATH start $APP_PROF
		;;
	restart_daemon)
		$ENTRY_PATH stop $APP_PROF
		$ENTRY_PATH daemon $APP_PROF
		;;
	remove)
		removeService
		;;
	*)
		printUsage
		echo
		exit 1
esac
